const loginForm=document.getElementById('loginForm');const loginModal=document.getElementById('loginModal');const mainContent=document.getElementById('mainContent');const logoutBtn=document.getElementById('logoutBtn');const userDisplay=document.getElementById('userDisplay');const gameSearch=document.getElementById('gameSearch');const searchResults=document.getElementById('searchResults');const seeMoreBtn=document.getElementById('seeMoreBtn');const gameGrid=document.getElementById('gameGrid');
const allGames=['The Last of Us Part II','Ghost of Tsushima','Elden Ring','Dark Souls III','God of War','Bloodborne','Uncharted 4','Horizon Zero Dawn','Spider-Man','Demon\'s Souls','Final Fantasy VII Remake','Kena Bridge of Spirits'];
let isLoggedIn=false;let moreGamesVisible=false;
loginForm.addEventListener('submit',(e)=>{e.preventDefault();const username=document.getElementById('username').value;const password=document.getElementById('password').value;if(username.trim()&&password.trim()){isLoggedIn=true;userDisplay.textContent=`Bem-vindo, ${username}`;loginModal.style.display='none';mainContent.style.display='block';loginForm.reset();}});
logoutBtn.addEventListener('click',()=>{isLoggedIn=false;loginModal.style.display='flex';mainContent.style.display='none';userDisplay.textContent='Bem-vindo';gameSearch.value='';searchResults.innerHTML='';searchResults.classList.remove('active');moreGamesVisible=false;seeMoreBtn.textContent='Ver Mais';seeMoreBtn.classList.remove('expanded');document.querySelectorAll('.hidden').forEach(el=>{el.classList.add('hidden');});});
gameSearch.addEventListener('input',(e)=>{const searchTerm=e.target.value.toLowerCase().trim();if(searchTerm===''){searchResults.innerHTML='';searchResults.classList.remove('active');return;}const filtered=allGames.filter(game=>game.toLowerCase().includes(searchTerm));searchResults.innerHTML='';if(filtered.length>0){searchResults.classList.add('active');filtered.forEach(game=>{const resultItem=document.createElement('div');resultItem.className='search-result-item';resultItem.textContent=game;resultItem.addEventListener('click',()=>{gameSearch.value='';searchResults.innerHTML='';searchResults.classList.remove('active');});searchResults.appendChild(resultItem);});}else{searchResults.classList.remove('active');}});
seeMoreBtn.addEventListener('click',()=>{const moreGamesElements=document.querySelectorAll('[id^="moreGames"]');if(moreGamesVisible){moreGamesElements.forEach(el=>{el.classList.add('hidden');});seeMoreBtn.textContent='Ver Mais';seeMoreBtn.classList.remove('expanded');moreGamesVisible=false;}else{moreGamesElements.forEach(el=>{el.classList.remove('hidden');});seeMoreBtn.textContent='Ver Menos';seeMoreBtn.classList.add('expanded');moreGamesVisible=true;}});
const timerDisplay=document.getElementById('timer');const startBtn=document.getElementById('startBtn');const stopBtn=document.getElementById('stopBtn');const resetBtn=document.getElementById('resetBtn');let elapsed=0;let intervalId=null;
function updateTimer(){const hours=Math.floor(elapsed/3600);const minutes=Math.floor((elapsed%3600)/60);const seconds=elapsed%60;timerDisplay.textContent=`${String(hours).padStart(2,'0')}:${String(minutes).padStart(2,'0')}:${String(seconds).padStart(2,'0')}`;}
function startTimer(){if(intervalId!==null) return;intervalId=setInterval(()=>{elapsed++;updateTimer();},1000);}
function stopTimer(){clearInterval(intervalId);intervalId=null;}
function resetTimer(){stopTimer();elapsed=0;updateTimer();}
startBtn.addEventListener('click',startTimer);stopBtn.addEventListener('click',stopTimer);resetBtn.addEventListener('click',resetTimer);updateTimer();