const loginForm=document.getElementById('loginForm');const loginModal=document.getElementById('loginModal');const mainContent=document.getElementById('mainContent');const logoutBtn=document.getElementById('logoutBtn');const userDisplay=document.getElementById('userDisplay');const gameSearch=document.getElementById('gameSearch');const searchResults=document.getElementById('searchResults');const seeMoreBtn=document.getElementById('seeMoreBtn');const gameSelect=document.getElementById('gameSelect');const selectedGameLabel=document.getElementById('selectedGameLabel');const accessedList=document.getElementById('accessedList');const tabButtons=document.querySelectorAll('.tab-btn');
const allGames=['GTA V','GTA San Andreas','GTA IV','GTA: Vice City','Red Dead Redemption 2','Red Dead Redemption','Bully','Max Payne 3','The Last of Us Part II','Ghost of Tsushima','Elden Ring','Dark Souls III','God of War','Bloodborne','Horizon Zero Dawn','Spider-Man','Demon\'s Souls','Final Fantasy VII Remake','Kena Bridge of Spirits','God of War Ragnarök'];
let isLoggedIn=false;let moreGamesVisible=false;
function setTab(tabId){document.querySelectorAll('.tab-content').forEach(section=>{section.classList.toggle('active',section.id===tabId)});tabButtons.forEach(button=>{button.classList.toggle('active',button.dataset.tab===tabId)});}
function updateGameSelection(value){selectedGameLabel.textContent=value||'Nenhum';}
function populateGameSelect(){gameSelect.innerHTML=allGames.map(game=>`<option value="${game}">${game}</option>`).join('');updateGameSelection(allGames[0]);}
function addAccessedGame(game){const item=document.createElement('div');item.className='list-item';item.textContent=`${game} - Último cronometrado`;accessedList.prepend(item);while(accessedList.children.length>8){accessedList.removeChild(accessedList.lastChild);}}
function populateSearchResults(filtered){searchResults.innerHTML='';if(filtered.length===0){searchResults.classList.remove('active');return;}searchResults.classList.add('active');filtered.forEach(game=>{const resultItem=document.createElement('div');resultItem.className='search-result-item';resultItem.textContent=game;resultItem.addEventListener('click',()=>{gameSearch.value='';searchResults.innerHTML='';searchResults.classList.remove('active');gameSelect.value=game;updateGameSelection(game);});searchResults.appendChild(resultItem);});}
function resetHiddenGames(){document.querySelectorAll('[id^="moreGames"]').forEach(el=>{el.classList.add('hidden');});seeMoreBtn.textContent='Ver Mais';seeMoreBtn.classList.remove('expanded');moreGamesVisible=false;}
loginForm.addEventListener('submit',e=>{e.preventDefault();const username=document.getElementById('username').value;const password=document.getElementById('password').value;if(username.trim()&&password.trim()){isLoggedIn=true;userDisplay.textContent=`Bem-vindo, ${username}`;loginModal.style.display='none';mainContent.style.display='block';loginForm.reset();}});
logoutBtn.addEventListener('click',()=>{isLoggedIn=false;loginModal.style.display='flex';mainContent.style.display='none';userDisplay.textContent='Bem-vindo';gameSearch.value='';searchResults.innerHTML='';searchResults.classList.remove('active');resetHiddenGames();populateGameSelect();});
gameSearch.addEventListener('input',e=>{const searchTerm=e.target.value.toLowerCase().trim();if(searchTerm===''){searchResults.innerHTML='';searchResults.classList.remove('active');return;}populateSearchResults(allGames.filter(game=>game.toLowerCase().includes(searchTerm)));});
seeMoreBtn.addEventListener('click',()=>{const moreGamesElements=document.querySelectorAll('[id^="moreGames"]');if(moreGamesVisible){resetHiddenGames();}else{moreGamesElements.forEach(el=>{el.classList.remove('hidden');});seeMoreBtn.textContent='Ver Menos';seeMoreBtn.classList.add('expanded');moreGamesVisible=true;}});
function formatTime(value){return String(value).padStart(2,'0');}
const timerDisplay=document.getElementById('timer');const startBtn=document.getElementById('startBtn');const stopBtn=document.getElementById('stopBtn');const resetBtn=document.getElementById('resetBtn');let elapsed=0;let intervalId=null;
function updateTimer(){const hours=Math.floor(elapsed/3600);const minutes=Math.floor((elapsed%3600)/60);const seconds=elapsed%60;timerDisplay.textContent=`${formatTime(hours)}:${formatTime(minutes)}:${formatTime(seconds)}`;}
function startTimer(){if(intervalId!==null) return;const currentGame=gameSelect.value;addAccessedGame(currentGame);intervalId=setInterval(()=>{elapsed++;updateTimer();},1000);}function stopTimer(){clearInterval(intervalId);intervalId=null;}function resetTimer(){stopTimer();elapsed=0;updateTimer();}
startBtn.addEventListener('click',startTimer);stopBtn.addEventListener('click',stopTimer);resetBtn.addEventListener('click',resetTimer);gameSelect.addEventListener('change',e=>updateGameSelection(e.target.value));tabButtons.forEach(button=>button.addEventListener('click',()=>setTab(button.dataset.tab)));
populateGameSelect();updateTimer();setTab('timerTab');